// Generated by CoffeeScript 1.9.2
(function() {
  var Vue, components, simpleReload;

  Vue = require("vue");

  simpleReload = require("simple-reload");

  components = {};

  module.exports = function(names, options) {
    var cwd, deep, fullname, i, len, name, ref, ref1, ref2, reload;
    if (options == null) {
      options = {};
    }
    cwd = (ref = options.cwd) != null ? ref : "./";
    reload = (ref1 = options.reload) != null ? ref1 : false;
    deep = (ref2 = options.deep) != null ? ref2 : false;
    if (reload) {
      components = {};
    }
    for (i = 0, len = names.length; i < len; i++) {
      name = names[i];
      fullname = require.resolve("" + name);
      if (fullname == null) {
        fullname = require.resolve("" + cwd + name);
      }
      loaded(reload ? simpleReload(fullname, deep) : require(fullname));
      if (components[name] == null) {
        components[name] = new Vue(loaded);
      }
    }
    return components;
  };

}).call(this);
